import { Work } from "@/types/work";

const permissibleWorks: Work[] = [
  {
    id: "WS001",
    vgpId: "WS001",
    workName: "Construction of Main Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS002",
    vgpId: "WS002",
    workName: "Repair & Maintenance of Main Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS003",
    vgpId: "WS003",
    workName: "Construction of Branch Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS004",
    vgpId: "WS004",
    workName: "Repair & Maintenance of Branch Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS005",
    vgpId: "WS005",
    workName: "Construction of Major Distributary Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS006",
    vgpId: "WS006",
    workName: "Repair & Maintenance of Major Distributary Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS007",
    vgpId: "WS007",
    workName: "Construction of Minor Distributary Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS008",
    vgpId: "WS008",
    workName: "Repair & Maintenance of Minor Distributary Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS009",
    vgpId: "WS009",
    workName: "Lining of Canal for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS010",
    vgpId: "WS010",
    workName: "Construction of Water Courses and Field Channels for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS011",
    vgpId: "WS011",
    workName: "Repair & Maintenance of Water Courses and Field Channels for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS012",
    vgpId: "WS012",
    workName: "Rejuvenation of Rivers, Rivulets and Nallahs",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Canals",
  },
  {
    id: "WS013",
    vgpId: "WS013",
    workName: "Construction of Flood or Diversion Channel for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Flood/Diversion Channels",
  },
  {
    id: "WS014",
    vgpId: "WS014",
    workName: "Repair & Maintenance of Flood or Diversion Channel for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Flood/Diversion Channels",
  },
  {
    id: "WS015",
    vgpId: "WS015",
    workName: "Construction of Flood Diversion Drain for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Flood/Diversion Channels",
  },
  {
    id: "WS016",
    vgpId: "WS016",
    workName: "Repair & Maintenance of Flood Diversion Drain for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Flood/Diversion Channels",
  },
  {
    id: "WS017",
    vgpId: "WS017",
    workName: "Construction of Storm Water Drain for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Flood/Diversion Channels",
  },
  {
    id: "WS018",
    vgpId: "WS018",
    workName: "Repair & Maintenance of Storm Water Drain for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Flood/Diversion Channels",
  },
  {
    id: "WS019",
    vgpId: "WS019",
    workName: "Construction of Boulder Check Dam for Individual",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS020",
    vgpId: "WS020",
    workName: "Construction of Boulder Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS021",
    vgpId: "WS021",
    workName: "Repair & Maintenance of Boulder Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS022",
    vgpId: "WS022",
    workName: "Construction of Earthen Check Dam for Individual",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS023",
    vgpId: "WS023",
    workName: "Construction of Earthen Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS024",
    vgpId: "WS024",
    workName: "Repair & Maintenance of Earthen Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS025",
    vgpId: "WS025",
    workName: "Construction of Gabion Check Dam for Individual",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS026",
    vgpId: "WS026",
    workName: "Construction of Gabion Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS027",
    vgpId: "WS027",
    workName: "Repair & Maintenance of Gabion Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS028",
    vgpId: "WS028",
    workName: "Construction of Masonry Check Dam for Individual",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS029",
    vgpId: "WS029",
    workName: "Construction of Masonry Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS030",
    vgpId: "WS030",
    workName: "Repair & Maintenance of Masonry Check Dam for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS031",
    vgpId: "WS031",
    workName: "Construction of Masonry Check Wall for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS032",
    vgpId: "WS032",
    workName: "Repair & Maintenance of Masonry Check Wall for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Check Dams",
  },
  {
    id: "WS033",
    vgpId: "WS033",
    workName: "Construction of Brushwood Gully Plug for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS034",
    vgpId: "WS034",
    workName: "Repair & Maintenance of Brushwood Gully Plug for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS035",
    vgpId: "WS035",
    workName: "Construction of Earthen Gully Plug for Individual",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS036",
    vgpId: "WS036",
    workName: "Construction of Earthen Gully Plug for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS037",
    vgpId: "WS037",
    workName: "Repair & Maintenance of Earthen Gully Plug for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS038",
    vgpId: "WS038",
    workName: "Construction of Stone Boulder Gully Plug for Individual",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS039",
    vgpId: "WS039",
    workName: "Construction of Stone Boulder Gully Plug for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS040",
    vgpId: "WS040",
    workName: "Repair & Maintenance of Stone Boulder Gully Plug for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Gully Plug",
  },
  {
    id: "WS041",
    vgpId: "WS041",
    workName: "Construction of Underground Dyke for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Underground Dyke",
  },
  {
    id: "WS042",
    vgpId: "WS042",
    workName: "Repair & Maintenance of Underground Dyke for Community",
    subTheme: "1). construction of canals, flood or diversion channels, check dams, gully plugs and underground dykes;",
    theme: "Category 1 -Water-Related Works (for Water Security)",
    type: "Underground Dyke",
  },
];

export async function getPermissibleWorks(): Promise<Work[]> {
  return permissibleWorks;
}

export default permissibleWorks;