import { Work } from "@/types/work";

export async function getAvailableWorks(): Promise<Work[]> {
  return [
    {
      id: "1",
      vgpId: "WS001",
      workName: "Construction of Boulder Check Dam for Individual",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      count: 3,
      type: "New",
      location: {
        lat: 15.27,
        lng: 75.12,
      },
    },
    {
      id: "2",
      vgpId: "WS002",
      workName: "Construction of Earthen Check Dam for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      count: 2,
      type: "New",
      location: {
        lat: 15.29,
        lng: 75.14,
      },
    },
    {
      id: "3",
      vgpId: "WS003",
      workName: "Construction of Percolation Tank",
      subTheme: "Water Resource Rejuvenation",
      theme: "Water Security",
      count: 4,
      type: "New",
      location: {
        lat: 15.25,
        lng: 75.10,
      },
    },
    {
      id: "4",
      vgpId: "WS004",
      workName: "Construction of Farm Pond",
      subTheme: "Rainwater Harvesting",
      theme: "Water Security",
      count: 3,
      type: "New",
      location: {
        lat: 15.24,
        lng: 75.13,
      },
    },
    {
      id: "5",
      vgpId: "WS005",
      workName: "Construction of Gabion Check Dam",
      subTheme: "Water Resource Rejuvenation",
      theme: "Water Security",
      count: 2,
      type: "New",
      location: {
        lat: 15.23,
        lng: 75.11,
      },
    },
    {
      id: "6",
      vgpId: "WS006",
      workName: "Construction of Irrigation Channels",
      subTheme: "Irrigation Infrastructure",
      theme: "Water Security",
      count: 3,
      type: "New",
      location: {
        lat: 15.26,
        lng: 75.15,
      },
    },
    {
      id: "7",
      vgpId: "WS007",
      workName: "Construction of Water Courses and Field Channels",
      subTheme: "Irrigation Infrastructure",
      theme: "Water Security",
      count: 1,
      type: "New",
      location: {
        lat: 15.28,
        lng: 75.16,
      },
    },
    {
      id: "8",
      vgpId: "WS008",
      workName: "Construction of Injection Well in Channels",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      count: 2,
      type: "New",
      location: {
        lat: 15.22,
        lng: 75.14,
      },
    },
    {
      id: "9",
      vgpId: "WS009",
      workName: "Construction of Bitumen Road",
      subTheme: "Rural Road Construction",
      theme: "Rural Infrastructure",
      count: 1,
      type: "New",
      location: {
        lat: 15.21,
        lng: 75.12,
      },
    },
    {
      id: "10",
      vgpId: "WS010",
      workName: "Construction of Collection Chamber",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      count: 2,
      type: "New",
      location: {
        lat: 15.20,
        lng: 75.13,
      },
    },
  ];
}

export async function getPermissibleWorks(): Promise<Work[]> {
  return [
    {
      id: "WS001",
      vgpId: "WS001",
      workName: "Construction of Boulder Check Dam for Individual",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS002",
      vgpId: "WS002",
      workName: "Construction of Boulder Check Dam for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS003",
      vgpId: "WS003",
      workName: "Repair & Maintenance of Boulder Check Dam",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "Repair",
    },
    {
      id: "WS004",
      vgpId: "WS004",
      workName: "Construction of Earthen Check Dam for Individual",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS005",
      vgpId: "WS005",
      workName: "Construction of Earthen Check Dam for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS006",
      vgpId: "WS006",
      workName: "Repair & Maintenance of Earthen Check Dam",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "Repair",
    },
    {
      id: "WS007",
      vgpId: "WS007",
      workName: "Construction of Gabion Check Dam for Individual",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS008",
      vgpId: "WS008",
      workName: "Construction of Gabion Check Dam for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS009",
      vgpId: "WS009",
      workName: "Repair & Maintenance of Gabion Check Dam",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "Repair",
    },
    {
      id: "WS010",
      vgpId: "WS010",
      workName: "Construction of Masonry Check Dam for Individual",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS011",
      vgpId: "WS011",
      workName: "Construction of Masonry Check Dam for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS012",
      vgpId: "WS012",
      workName: "Repair & Maintenance of Masonry Check Dam",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "Repair",
    },
    {
      id: "WS013",
      vgpId: "WS013",
      workName: "Construction of Brushwood Gully Plug for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS014",
      vgpId: "WS014",
      workName: "Repair & Maintenance of Brushwood Gully Plug",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "Repair",
    },
    {
      id: "WS015",
      vgpId: "WS015",
      workName: "Construction of Earthen Gully Plug for Individual",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS016",
      vgpId: "WS016",
      workName: "Construction of Earthen Gully Plug for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
    {
      id: "WS017",
      vgpId: "WS017",
      workName: "Repair & Maintenance of Earthen Gully Plug",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "Repair",
    },
    {
      id: "WS018",
      vgpId: "WS018",
      workName: "Construction of Stone Boulder Gully Plug for Community",
      subTheme: "Water Infrastructure Construction",
      theme: "Water Security",
      type: "New",
    },
  ];
}